### ISSUE TITLE
Error using compiling mac osx

### ISSUE THREAD

**Issue by stijndehaes** [cessen/openexr-rs#28]
Hey,

I tried to use your library in one of my projects. I used openexr installed via homebrew and got a compile error. Could you help me? 

```
error: failed to run custom build command for `openexr-sys v0.5.0`
process didn't exit successfully: `/Users/stijndehaes/rust/ray-tracer/target/debug/build/openexr-sys-e8532d8c35689436/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/local/Cellar/openexr/2.2.1_1/lib
cargo:rustc-link-search=native=/usr/local/Cellar/ilmbase/2.2.1/lib
cargo:rustc-link-lib=IlmImf
cargo:rustc-link-lib=Imath
cargo:rustc-link-lib=Half
cargo:rustc-link-lib=Iex
cargo:rustc-link-lib=IexMath
cargo:rustc-link-lib=IlmThread
cargo:rustc-link-search=native=/usr/lib
cargo:rustc-link-lib=z
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CXX_x86_64-apple-darwin = None
CXX_x86_64_apple_darwin = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CXXFLAGS_x86_64-apple-darwin = None
CXXFLAGS_x86_64_apple_darwin = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("true")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "c_wrapper" "-I" "/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR" "-I" "/usr/local/Cellar/ilmbase/2.2.1/include/OpenEXR" "-I" "/usr/local/Cellar/ilmbase/2.2.1/include/OpenEXR" "-std=c++0x" "-Wall" "-Wextra" "-o" "/Users/stijndehaes/rust/ray-tracer/target/debug/build/openexr-sys-830ad403a950ee27/out/c_wrapper/cexr.o" "-c" "c_wrapper/cexr.cpp"
cargo:warning=In file included from c_wrapper/cexr.cpp:11:
cargo:warning=In file included from /usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfOutputFile.h:49:
cargo:warning=In file included from /usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfGenericOutputFile.h:40:
cargo:warning=In file included from /usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfXdr.h:108:
cargo:warning=/usr/local/Cellar/ilmbase/2.2.1/include/OpenEXR/half.h:462:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
cargo:warning=        register int e = (x.i >> 23) & 0x000001ff;
cargo:warning=        ^~~~~~~~~
cargo:warning=/usr/local/Cellar/ilmbase/2.2.1/include/OpenEXR/half.h:473:6: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
cargo:warning=            register int m = x.i & 0x007fffff;
cargo:warning=            ^~~~~~~~~
cargo:warning=In file included from c_wrapper/cexr.cpp:16:
cargo:warning=c_wrapper/rust_istream.hpp:26:19: error: virtual function 'tellg' has a different return type ('std::uint64_t' (aka 'unsigned long long')) than the function it overrides (which has return type 'Imath_2_2::Int64' (aka 'unsigned long'))
cargo:warning=    std::uint64_t tellg();
cargo:warning=    ~~~~~~~~~~~~~ ^
cargo:warning=/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfIO.h:114:19: note: overridden virtual function is here
cargo:warning=    virtual Int64       tellg () = 0;
cargo:warning=            ~~~~~       ^
cargo:warning=In file included from c_wrapper/cexr.cpp:16:
cargo:warning=c_wrapper/rust_istream.hpp:27:10: warning: 'RustIStream::seekg' hides overloaded virtual function [-Woverloaded-virtual]
cargo:warning=    void seekg(std::uint64_t pos);
cargo:warning=         ^
cargo:warning=/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfIO.h:122:18: note: hidden overloaded virtual function 'Imf_2_2::IStream::seekg' declared here: type mismatch at 1st parameter ('Imath_2_2::Int64' (aka 'unsigned long') vs 'std::uint64_t' (aka 'unsigned long long'))
cargo:warning=    virtual void        seekg (Int64 pos) = 0;
cargo:warning=                        ^
cargo:warning=In file included from c_wrapper/cexr.cpp:17:
cargo:warning=c_wrapper/rust_ostream.hpp:25:27: error: virtual function 'tellp' has a different return type ('std::uint64_t' (aka 'unsigned long long')) than the function it overrides (which has return type 'Imath_2_2::Int64' (aka 'unsigned long'))
cargo:warning=    virtual std::uint64_t tellp ();
cargo:warning=            ~~~~~~~~~~~~~ ^
cargo:warning=/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfIO.h:184:19: note: overridden virtual function is here
cargo:warning=    virtual Int64       tellp () = 0;
cargo:warning=            ~~~~~       ^
cargo:warning=In file included from c_wrapper/cexr.cpp:17:
cargo:warning=c_wrapper/rust_ostream.hpp:26:18: warning: 'RustOStream::seekp' hides overloaded virtual function [-Woverloaded-virtual]
cargo:warning=    virtual void seekp (std::uint64_t pos);
cargo:warning=                 ^
cargo:warning=/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfIO.h:192:18: note: hidden overloaded virtual function 'Imf_2_2::OStream::seekp' declared here: type mismatch at 1st parameter ('Imath_2_2::Int64' (aka 'unsigned long') vs 'std::uint64_t' (aka 'unsigned long long'))
cargo:warning=    virtual void        seekp (Int64 pos) = 0;
cargo:warning=                        ^
cargo:warning=c_wrapper/cexr.cpp:33:53: error: allocating an object of abstract class type 'RustIStream'
cargo:warning=        *out = reinterpret_cast<CEXR_IStream *>(new RustIStream(reader, read_ptr, seekp_ptr));
cargo:warning=                                                    ^
cargo:warning=/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfIO.h:122:18: note: unimplemented pure virtual method 'seekg' in 'RustIStream'
cargo:warning=    virtual void        seekg (Int64 pos) = 0;
cargo:warning=                        ^
cargo:warning=c_wrapper/cexr.cpp:58:53: error: allocating an object of abstract class type 'RustOStream'
cargo:warning=        *out = reinterpret_cast<CEXR_OStream *>(new RustOStream(writer, write_ptr, seekp_ptr));
cargo:warning=                                                    ^
cargo:warning=/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR/ImfIO.h:192:18: note: unimplemented pure virtual method 'seekp' in 'RustOStream'
cargo:warning=    virtual void        seekp (Int64 pos) = 0;
cargo:warning=                        ^
cargo:warning=4 warnings and 4 errors generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "c_wrapper" "-I" "/usr/local/Cellar/openexr/2.2.1_1/include/OpenEXR" "-I" "/usr/local/Cellar/ilmbase/2.2.1/include/OpenEXR" "-I" "/usr/local/Cellar/ilmbase/2.2.1/include/OpenEXR" "-std=c++0x" "-Wall" "-Wextra" "-o" "/Users/stijndehaes/rust/ray-tracer/target/debug/build/openexr-sys-830ad403a950ee27/out/c_wrapper/cexr.o" "-c" "c_wrapper/cexr.cpp" with args "c++" did not execute successfully (status code exit code: 1).

', /Users/stijndehaes/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::begin_panic
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::try::do_call
             at libstd/panicking.rs:521
   7: gcc::fail
             at /Users/stijndehaes/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670
   8: <alloc::heap::Heap as alloc::allocator::Alloc>::oom
             at /Users/stijndehaes/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:783
   9: build_script_build::main
             at ./build.rs:88
  10: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  12: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  13: rust_panic
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  14: build_script_build::main


Process finished with exit code 101
```

**Comment by stijndehaes** [comment]
The issue is fixed on the master branch so I will wait for a new release. Until then I will use the master branch to build my preject. Thank you for the awesome work
